### ISSUE TITLE
NUM_BATCH and num_test_episodes

### ISSUE THREAD

**Issue by watashihageteru** [andrew-j-levy/Hierarchical-Actor-Critc-HAC-#4]
I'd like to know the role of parameters: NUM_BATCH and num_test_episodes in "run_HAC.py", 

Is there any difference for the learning effect between procedure A and B?
A) NUM_BATCH = 1  and num_test_episodes = 1000
B) NUM_BATCH = 10 and num_test_episodes = 100

**Comment by andrew-j-levy** [comment]
Hello and thanks for your question.  The parameters NUM_BATCH, TEST_FREQ, num_test_episodes, and num_exploration episodes (in "design_agent_and_env.py") control the training schedule of the agent.  Under default settings, the agent will train for NUM_BATCH = 1000 batches.  Because TEST_FREQ = 2, the agent will alternate between an exploration batch and an evaluation batch.  During an exploration batch, the agent will actually learn.  The agent will add exploration noise to its policy, collect experience transitions, and update the actor and critic networks.  Each exploration batch will consist of "num_exploration_episodes" episodes.  During an evaluation batch, an agent will not collect any experience transitions nor make any updates to the actor and critic networks.  The agent will simply follow its policy for "num_test_episodes" and the percentage of successful episodes (i.e., episodes in which the agent has achieved the end goal) will be recorded.  The purpose of the evaluation batch is thus to determine how good the current policy is and not to do any learning.

The default setting NUM_BATCH = 1000 is too large and I will lower this in my next update.  Agents in the inverted pendulum and UR5 Reacher tasks only need a few hundred episodes to learn the task so NUM_BATCH = 40 and num_exploration_episodes = 50, which together results in 40 / 2 * 50 = 1000 episodes of exploration should be plenty.  Setting NUM_BATCH = 1 would only give the agent 50 episodes of exploration, which is not enough to learn an effective policy.

num_test_episodes just represents how large of a sample you would like when you are evaluating the policy you have learned.  Each episode uses a random initial start state and end goal state (except in inverted pendulum in which the goal state is always at the top of the pendulum).  In the environments I have provided, num_test_episodes = 100 should provide a large enough sample of different (initial state, end goal) combinations.

Also, please note you do not need to wait until the program terminates to track the progress of the agent.  At the end of each evaluation batch, the percentage of successful episodes is printed and pickled in the "performance_log.p" file.

Hope that helps.
